const TestCase = require("../models/testCases");

exports.addTestCase = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    res.status(400).json({ message: error.message, success: false });
  }
};

exports.editTestCase = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    res.status(400).json({ message: error.message, success: false });
  }
};

exports.deleteTestCase = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    res.status(400).json({ message: error.message, success: false });
  }
};

exports.getTestCasesByProblem = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    res.status(400).json({ message: error.message, success: false });
  }
};
